heat_template_version: 2015-10-15

parameters:

  bmc_prefix:
    type: string

  private_net:
    type: string

resources:
  bmc_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        list_join:
        - '_'
        - - {get_param: bmc_prefix}
          - 'sg'
      description: SSH, ping, IPMI from the same net
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: udp
        port_range_min: 623
        port_range_max: 623
        remote_ip_prefix: {get_param: private_net}

  private_bmc_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - '_'
        - - 'utility'
          - {get_param: bmc_prefix}
      network: {get_param: private_net}
      security_groups:
      - {get_resource: bmc_sg}
      port_security_enabled: False

outputs:
  port:
    value:
    - {port: {get_resource: private_bmc_port}}
  ip_address:
    value: {get_attr: [private_bmc_port, fixed_ips, 0, ip_address]}
